### ISSUE TITLE
Spin Custom Template Run Localy

### ISSUE THREAD

**Issue by YevheniiVolosiuk** [serversideup/spin#116]
### Current Behavior

I am truing run a install.sh script and start to test it.
But  after running `spin new wordpress-spin --local spin-template-wordpress-basic/`

I am getting error like on screeen also for 

.dockerignore: No such file or directory

Note: if I create manually wordpress-spin folder and will add .gitignore and .dockerignore it will work 

![image](https://github.com/user-attachments/assets/66cca70b-c160-4f09-bbd7-84a0d8f0adaa)

### Expected Behavior

Correct run and possibility to run install.sh file for a custom template

### Steps To Reproduce

1. make custom template start files how in docs
2. Run `spin new wordpress-spin --local spin-template-wordpress-basic/`

### Environment

```markdown
Spin Version:
v2.2.0 [stable] (User Installed)

Operating System Version:
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Docker Info:
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
Client:
 Version:    27.2.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2-desktop.2
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     /usr/local/lib/docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /usr/local/lib/docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /usr/local/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.13.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 27.2.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.153.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 7.761GiB
 Name: docker-desktop
 ID: 144bc0d0-ab8e-4c4a-8518-2f6148e0fb6d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///var/run/docker-cli.sock
 Experimental: true
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by jaydrogers** [comment]
Can you update to `v2.2.2` and try again?

Just launched this https://github.com/serversideup/spin/releases/tag/v2.2.2

**Comment by YevheniiVolosiuk** [comment]
Hi,

Seems it is still a problem.

![image](https://github.com/user-attachments/assets/df4999e8-00c1-4d43-96b9-625132e53030)

**Comment by jaydrogers** [comment]
I might have to circle back on this one. For the time being, create a `.dockerignore` file in your project and be sure to include anything that doesn't need to be in the Docker image that you will build.

I might move this requirement out all together and have the truth all come from the template itself

**Comment by YevheniiVolosiuk** [comment]
When I create the main folder for a project `wordpress-spin`

I am not get error with .gitignore and .dockerignore

command what I use it is 

`spin new wordpress-spin --local spin-template-wordpress-basic/`

An error happened when I tried to create the main project folder "wordpress-spin" like in the command.

**Comment by YevheniiVolosiuk** [comment]
> When I create the main folder for a project `wordpress-spin`
> 
> I am not get error with .gitignore and .dockerignore
> 
> command what I use it is
> 
> `spin new wordpress-spin --local spin-template-wordpress-basic/`
> 
> An error happened when I tried to create the main project folder "wordpress-spin" with the command.
> 
> ![image](https://private-user-images.githubusercontent.com/77569229/375476531-bf1b6a30-6591-43b6-891d-c1f60fb1374f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMTM2MzgsIm5iZiI6MTcyOTExMzMzOCwicGF0aCI6Ii83NzU2OTIyOS8zNzU0NzY1MzEtYmYxYjZhMzAtNjU5MS00M2I2LTg5MWQtYzFmNjBmYjEzNzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDIxMTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNzAzNzllMmYzZjMxNmRmOGIwMGI5ODZiMzY4ZTQ1M2ZiMGYwZjZlNzNjNDE3ZTI3ZDc0YjllODVmYmI2MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6R9XqZMB5Ff9JfuoFDY_jRxjX9oYSirS_zC6-RFtVFs)

fixed it with a simple check 

![image](https://github.com/user-attachments/assets/017fa888-04b1-4ff6-9fa3-0a83ddc7aee3)

**Comment by jaydrogers** [comment]
Awesome!! Thanks for posting your solution!
