### ISSUE TITLE
Shell is also a script language

### ISSUE THREAD

**Issue by szepeviktor** [serversideup/spin#15]
### Current Behavior

... although it has much less tools than other script languages

### Expected Behavior

- [x] indent with 4 spaces - I hope 2 is not enough for you
- [ ] move curly brace to a separate line
- [ ] add [shebang and script headers](https://github.com/szepeviktor/debian-server-tools/blob/master/tools/ghurl#L1-L12)
- [ ] move things without side effect (function declaration are not executed!) to the top
- [ ] nice, decorative comments could be removed, use descriptive function names instead
- [ ] Introduce shellcheck in CI

```bash
############################################################################################################
# nice, decorative comment
############################################################################################################
```

**Comment by szepeviktor** [comment]
After #14 we could run
`shfmt --indent=4 --binary-next-line --write bin/spin tools/upgrade.sh tools/install.sh`

**Comment by szepeviktor** [comment]
I leave the remaining 5 item to you.

**Comment by jaydrogers** [comment]
Moved to feature ideas: https://github.com/serversideup/spin/discussions/46
