### ISSUE TITLE
Create new Nuxt content site for documentation

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/spin#25]
# Problem
- Spin's current site is running an older version of Nuxt content
- In order to build Spin 2.0, we should write the process on how it works first, then build the code around the process

# Proposed Solution
- [x] @danpastori: Create a new Nuxt content site following our Docker PHP project (https://serversideup.net/open-source/docker-php/)
- [x] @jaydrogers: Create automated deployments that build previews for CloudFlare pages
- [x] @jaydrogers Create new logo and configure new colors

**Comment by danpastori** [comment]
@jaydrogers I pushed the initial commit for the docs site. Here's what you will need to add:

- [ ] OG Images -> /images/social-image.jpg
- [ ] OG Meta Data -> All content files and in docs/layouts/marketing.vue & docs/layouts/docs.vue.

Everything else should be handled exactly the same as Docker PHP.

**Comment by jaydrogers** [comment]
Thanks for the list Dan!

I have these changes published on https://github.com/serversideup/spin/tree/release/2.0
