### ISSUE TITLE
Design structure for configuration files with Spin

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/spin#26]
# 😕 Problem
- `spin` needs a very easy way to configure settings for infrastructure, but we do not have a standard of what this should look like

### Every project will need the following configurations:
1. Global spin variables (for all hosts)
2. Host specific variables (support many hosts, which means many files)
3. Hosts inventory file ([what Ansible calls it](https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html), containing a list of all hosts)
4. Service configurations (things like Traefik that need config files)

# 🎯 Design goals
- All configurations should be stored in the repository and version controlled
- This includes secrets that configure a server
- Spin shall use `spin vault` (a shortcut to 'ansible vault') to help users encrypt their secrets (with AES256) and keep them in version control

# 💪How it works now
We currently have this concept working, but we need to merge everything into one project repository. This comes with defining standards of what project directories will look like.

# 🕊️ Proposed Solution (Draft Status & Open for comment)
```
├── .editorconfig
├── .env.example
├── .gitattributes
├── 🚨 .gitignore (need to modify this to exclude .vault-password)
├── ✨ .infrastructure
│		└──dev
│			└── traefik
│				├── certificates
│				└── traefik.yml
│		└──host_vars
│			├── myserver01.example.com
│			└── myserver02.example.com		
│		└──hosts
├── README.md
├── app
├── artisan
├── bootstrap
├── composer.json
├── config
├── database
├── ✨ docker-compose.yml
├── ✨ docker-compose.dev.yml
├── ✨ docker-compose.ci.yml
├── ✨ docker-compose.prod.yml
├── package.json
├── phpunit.xml
├── public
├── resources
├── routes
├── ✨ spin.config.yml
├── storage
├── tests
├── vite.config.js
└── ✨ .vault-password (optional for using "ansible vault")

```

## Using `spin` in a project
- `spin` will be able to function globally on a system machine or be included as a system dependency
- Using `spin` outside of a project is possible, it simply requires at least a `docker-compose.yml` file to exist
- If the user is attempting to run `spin provision` or `spin maintain`, then it requires a `spin.config.yml`, which will be the "all" setting for Ansible

### Directories in a project
- Anything highlighted with a ✨ is a new file to be created in a Laravel example project
- Anything with a 🚨 means it needs to be modified if the user chooses to use the feature
- An `_infrastructure` folder will be created where users can include external environment configs (like Traefik) but also have a place for `host_vars` for Ansible to use

### Docker Compose files
- Docker Compose files will be at the root of the project and follow the standards of [Docker Compose Overrides](https://docs.docker.com/compose/extends/)
- `spin` will default to running `docker compose -f docker-compose.yml -f docker-compose.dev.yml`, but it can easily be overwrittien to different environments using an environment variable

# 🙌 Looking for comments
1. Do you like the `_infrastructure` folder standard?
5. Does the `spin.config.yml` make sense to have it in the project root?

**Comment by joelclermont** [comment]
I like the name `infrastructure`. Is the `_` prefix just to make it jump up to the top of the folder list? Other tools I've seen either use a `.` like `.github` or don't prefix at all like AWS Copilot and the `copilot` folder. I don't have a strong feeling against the `_`, just an observation.

I also like `spin.config.yml` in the project root. At the same level as docker compose files makes sense.

**Comment by jaydrogers** [comment]
Thanks @joelclermont! I greatly appreciate the feedback.

The idea of `_` was to just move it to the top of the list in a project, but I honestly think that will rile up a lot of people.

Knowing how aggressive the development world can be sometimes about the smallest details, do you think it's just safer to move it into a folder called `infrastructure`?

**Comment by joelclermont** [comment]
Yes, I'd probably just call it `infrastructure`. We already have a `docker` folder in our app for our current setup. The lack of a prefix has not been an issue for us. Laravel doesn't have that many top-level folders, so it doesn't really get lost.

**Comment by jaydrogers** [comment]
After further discussion with some other folks, I think `.infrasturcture` will be best. It does the following things:

1. It moves the folder near the top
2. It follows a standard of `.github` and `.gitlab`, who also have infrastructure files in there

I appreciate the feedback and more coming soon 😃

**Comment by s4ke** [comment]
At first sight - how will secrets and configs (as defined by swarm) be handled by this?

How will users keep environments in sync?

How will multiple prod deployments of the same app be handled?

**Comment by jaydrogers** [comment]
> At first sight - how will secrets and configs (as defined by swarm) be handled by this?

I will create `spin vault` which will alias to `ansible vault`. I would assume they would commit these secrets directly to the repo (with ansible vault of course)

> How will users keep environments in sync?

Can you give an example by what you mean in sync?

> How will multiple prod deployments of the same app be handled?

I do have other resources that people can customize: https://www.youtube.com/watch?v=TEnO2jPwt-c

**Comment by jaydrogers** [comment]
For further clarity, here is a Work in Progress example of a Laravel app: https://github.com/serversideup/spin-laravel-example/pull/1

**Comment by jaydrogers** [comment]
This is complete 🥳

For a demo on how this works, see this Laravel example:

<a href="https://www.youtube.com/watch?v=I_dq-kRDztI">![Youtube player](https://github.com/serversideup/spin/assets/3174134/987afe17-6910-4c22-9373-b730f4f8ad73)</a>
