### ISSUE TITLE
Update Nuxt Content to 3.8

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/spin#34]
# Problem
- Similiar to [serversideup/php](https://github.com/serversideup/docker-php/), we need Nuxt content updated to 3.8

# Proposed Solution

### Technical Updates
- [x] Ensure Nuxt Content is updated to 3.8
- [x] Update Node to use `v20` (ensure `.nvmrc` file is udpated)
- [x] Ensure deployments are working (**⚠️ these are deployed differently than serversideup/php** -- CloudFlare pages directly deploys it)
- [ ] Ensure the sitemap is generating correctly

### Social Images
![Image](https://github.com/serversideup/spin/assets/3174134/ad7c748e-c24a-408f-8d99-76aa2617f412)

- [x] Use an OG Image generator to create social images

#### Figma Asset
https://www.figma.com/file/Oi4qvxnCYkhTehVGI61l4Q/Spin-Website?type=design&node-id=703-600&mode=design&t=2V3I4c1hs6el7rLt-11

**Comment by danpastori** [comment]
@jaydrogers We will have to get the env set up for Algolia at some point. We will need the variables defined here: https://github.com/serversideup/docker-php/issues/131

This means we also need to apply under our Server Side Up Account: https://docsearch.algolia.com/

Let me know if you want to connect and get that taken care of at some point.
