### ISSUE TITLE
Use ncurses' tput for colors

### ISSUE THREAD

**Issue by szepeviktor** [serversideup/spin#4]
https://github.com/serversideup/spin/blob/bccece6380d0958448ce17eacb9b44b06bc52b73/bin/spin#L101-L114

Use tput instead!
https://github.com/natelandau/shell-scripting-templates/blob/6fe9e43cb59808b511e6742eb6820bdc66150359/utilities/alerts.bash#L29-L35

Do not _talk_ to OS-es without ncurses :)

**Comment by jaydrogers** [comment]
Thanks for the feedback! This is my first time messing around with colors in a terminal, so lots to learn 😅

I basically followed the same code (most of it was copy/paste) from OhMyZSH.

https://github.com/ohmyzsh/ohmyzsh/blob/841f3cb0bb7663fa1062ffc59acb7b4581dc1d0f/tools/install.sh#L156-L182

Any articles or reasons explaining one vs the other?

**Comment by szepeviktor** [comment]
> reasons

It is easy to see. What do want on your screen? `'\033[38;5;196m'` vs. `tput setaf 7`
That's it.

**Comment by jaydrogers** [comment]
LOL! Totally agree!

Thanks, I will definitely take a look into this and will convert.

**Comment by jaydrogers** [comment]
Thanks for the feedback on this, but I am going to close it for now. I already went through the headache of going through this and it works fine for now. If I make changes, I will definitely update it to this.

I appreciate you pointing this out for me for the future though!
