### ISSUE TITLE
Connect Algolia Search

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/spin#43]
![image](https://github.com/serversideup/spin/assets/3174134/bdda0ae9-6612-4b11-8ceb-e1923e1fe74b)

              @jaydrogers We will have to get the env set up for Algolia at some point. We will need the variables defined here: https://github.com/serversideup/docker-php/issues/131

This means we also need to apply under our Server Side Up Account: https://docsearch.algolia.com/

Let me know if you want to connect and get that taken care of at some point.

_Originally posted by @danpastori in https://github.com/serversideup/spin/issues/34#issuecomment-1856708543_

**Comment by jaydrogers** [comment]
@danpastori We should get the docs search working. I'm having a lot of people ask questions because they can't search the docs.

I emailed Algolia:

```
Hello,

We have multiple open source projects that we would like to use Algolia for. We just added another one here: https://serversideup.net/open-source/spin/

Do we need to apply for each project? Or can we create multiple indexes with a single approval?
```

**Comment by danpastori** [comment]
@jaydrogers let me know what they say. Once we have the keys, it will be really easy to add

**Comment by jaydrogers** [comment]
@danpastori: Is there a way that we can run this without Algolia? Their product is very confusing.

Can we use this experimental package instead? https://content.nuxt.com/usage/search

**Comment by danpastori** [comment]
@jaydrogers I opened a PR (https://github.com/serversideup/spin/pull/71) which solves this using the new Nuxt Content search.

Cmd + K and clicking a search button will open the menu. Let me know your thoughts and feel free to merge when ready.
