### ISSUE TITLE
Responsive image is not loading correctly

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/spin#44]
### URL
https://serversideup.net/open-source/spin/docs/getting-started/how-spin-works

### Desktop
Not sure why this isnt appearing because it did before.
![image](https://github.com/serversideup/spin/assets/3174134/11759b2a-5a02-4b2e-9a5f-10ef1482355e)

### Mobile
Before the merge, the image was not appearing correctly on mobile

![IMG_7042](https://github.com/serversideup/spin/assets/3174134/e223b02a-9f93-4bc7-822b-dfc16d5d1486)

**Comment by danpastori** [comment]
@jaydrogers These bugs are fixed and deployed
