### ISSUE TITLE
Add Feature Cards to Main Docs Index

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/spin#45]
![image](https://github.com/serversideup/spin/assets/3174134/86c0e7b6-0edf-4e62-9b0e-5bd0adb1cc20)

## Similar to Docker PHP
![image](https://github.com/serversideup/spin/assets/3174134/b8434b73-fb61-413c-b797-c022542f34b1)

**Comment by danpastori** [comment]
@jaydrogers The grid is now available with
```
::feature-grid
::
```
