### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by shinsenter** [serversideup/spin#5]
First, congratulations on your first official release! You're doing great! 🥳

## General
After reading through your documentation, I realized that there may be a few real-life cases where the project can not implement (or is difficult to archive). That's why I decided to create this issue, for discussion purposes.

---

## Use case

Let's assume that we need to build the following environments with the same code-base using the popular framework Laravel.
The general requirement is that they should be as consistent as possible, and easy to operate.

### General requirements
 - [ ] Use a redis instance as a cache service
 - [ ] Limit size of log files for all containers
 - [ ] Automatically restart the container when it fails
 - [ ] Simply launch docker for different environments
 - [ ] Friendly with docker compose CLI

### Production
 - [ ] One web backend can scale to many instances
 - [ ] Use traefik as gateway, support HTTP and HTTPS
 - [ ] No need for other services like mysql, phpmyadmin attached
<img width="374" alt="Screen Shot 2022-01-27 at 10 59 05" src="https://user-images.githubusercontent.com/2082119/151278292-a9930410-99b5-4fe6-8c4d-db074a0ff7f3.png">

### Local
 - [ ] Two instances for web backend to test 2 different branches of code
 - [ ] The first web backend runs on port 8001
 - [ ] Second web backend running on port 8002
 - [ ] Use additional mysql, phpmyadmin services for local development
 - [ ] phpmyadmin running on port 8080
 - [ ] No need to use traefik as gateway as each backend runs on its own port
<img width="352" alt="Screen Shot 2022-01-27 at 10 59 17" src="https://user-images.githubusercontent.com/2082119/151278324-db71fbe9-7f40-4824-b531-ff4f6593af19.png">

### Debug
 - [ ] A web backend instance, running on port 80
 - [ ] A blackfire service for profiling web backend
 - [ ] Use additional mysql, phpmyadmin services for local development
 - [ ] phpmyadmin running on port 8080
 - [ ] No need to use traefik as gateway as each backend runs on its own port
<img width="358" alt="Screen Shot 2022-01-27 at 10 59 43" src="https://user-images.githubusercontent.com/2082119/151278347-efd595ed-a481-46d6-80cc-9b2078e95c29.png">

This setup should follow the official Docker guidlines as much as possible.

## What is expected?
I am able to implement this setup using spin.

**Comment by shinsenter** [comment]
As discussed earlier, I have created a gists for this.
You can refer to my ideas posted at [Docker directory structure for multiple environments](https://gist.github.com/shinsenter/ac177a7df561674a2bdd3692cf9e0059).

**Comment by jaydrogers** [comment]
Thanks I will take a look and respond to you soon. Busy day for me today 😅
