### ISSUE TITLE
(pedantic) Typo in "How spin works" image

### ISSUE THREAD

**Issue by jacovdbergh** [serversideup/spin#50]
### Current Behavior

In the readme there's a typo, sever instead of server, in the following image:

![image](https://github.com/serversideup/spin/assets/24895833/215c847d-e603-45d7-acf4-bd5786e1eb50)

### Expected Behavior

No typos :)

### Steps To Reproduce

N/A

### Environment

```markdown
N/A
```

### Anything else?

Thanks for all the work on this project, looking forward to give it a spin!

**Comment by jaydrogers** [comment]
Thanks for pointing that out! It's early AM here and I looked at that image 5 times before it registered 😆
