### ISSUE TITLE
Spin 2.0 beta fails to install on Mac OS X 

### ISSUE THREAD

**Issue by danmatthews** [serversideup/spin#52]
### Current Behavior

![CleanShot 2024-01-04 at 19 23 58@2x](https://github.com/serversideup/spin/assets/149426/3ba077a8-e697-4a86-8c15-c2a715b3b38e)

Running the install command in the docs using either `curl` or `wget` results in a single `Cloning Spin "v2.0.0-beta-2"...` message before exiting.

Mac OS X Sonoma 14.0
Tried in both Mac's Terminal and Warp Terminal
Using Oh-my-zsh

### Expected Behavior

Spin will install.

### Steps To Reproduce

Run `bash -c "$(curl -fsSL https://raw.githubusercontent.com/serversideup/spin/main/tools/install.sh)"` in any mac terminal.

Tried with:

- Warp terminal. (zsh)
- Built in mac os x terminal (zsh)
- Orbstack running and docker desktop closed
- Docker desktop running with orbstack closed.

`docker` is a available on the command line.

### Environment

```markdown
Unable to run spin debug as it won't install.

`zsh 5.9 (x86_64-apple-darwin23.0)`

`Docker version 24.0.7, build afdd53b`


GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
Copyright (C) 2007 Free Software Foundation, Inc.
```
```


### Anything else?

Sorry this is so vague, let me know if you need anything else to debug.

**Comment by jaydrogers** [comment]
Weird!! Of course it works on my machine 😆

![image](https://github.com/serversideup/spin/assets/3174134/07268763-c0d8-42fd-945d-9d593455e177)

Let me see if I can ship a feature to put the installer in a debug mode.

I assume `git` is installed locally?

**Comment by danmatthews** [comment]
`tis indeed!

`git version 2.39.0`

**Comment by danmatthews** [comment]
Looks like using some `echo` magic it's here it fails:

https://github.com/serversideup/spin/blob/main/tools/install.sh#L241

```
  # Add the remote repository
  git remote add -f origin "$REMOTE" > /dev/null 2>&1
```

**Comment by danmatthews** [comment]
Oh ok, we're in business ✅ 

Looks like maybe there was already a `.spin` directory in my home directory with some contents in, not entirely sure why.

**Comment by jaydrogers** [comment]
Thanks for the updates! I knew I ran into this issue somehow and forgot how I did it.

Maybe I will just put in a check if the folder exists already on install.

I will put this on my radar for the next release 👍

**Comment by jaydrogers** [comment]
Tracking here 🥳

https://github.com/serversideup/spin/discussions/54
