### ISSUE TITLE
(Minor) Error output during Linux install

### ISSUE THREAD

**Issue by oldskool73** [serversideup/spin#6]
## Issue description
When installing on Linux following the OSX install instructions per the docs, an error is shown in the output:

```
➜ sh -c "$(curl -fsSL https://raw.githubusercontent.com/serversideup/spin/main/tools/install.sh)"

sh: 185: [: stable: unexpected operator
Cloning Spin...
...etc
```

The install seems to continue fine though and the repo is pulled.

## Environment

- Operating System Version:
  - Pop_OS 21.10
  - Zsh
  - Gnome Terminal

## Steps to reproduce the issue

1.  As above, run curl install command

## What is expected?
Install completes with no error output

**Comment by jaydrogers** [comment]
Thanks for your bug report! I will take a look into this.

I appreciate you filling out the bug report template. It helps me out a ton! ❤️

**Comment by jaydrogers** [comment]
Fixed this 😃

It was just an extra equal sign that I had in there.

For some reason it did not display on macOS. More details on the issue here: https://stackoverflow.com/questions/18102454/why-am-i-getting-an-unexpected-operator-error-in-bash-string-equality-test
