### ISSUE TITLE
/usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by quantumwebco** [serversideup/spin#83]
### Current Behavior

In WSL2 running the commands from the docs ```bash -c "$(curl -fsSL https://raw.githubusercontent.com/serversideup/spin/main/tools/install.sh)"``` seems to install fine, but when running ```~/spin/bin/spin``` I just get the error ```/usr/bin/env: ‘bash\r’: No such file or directory``` like it's installed it with windows line endings

I've tried rm -rf the .spin directory and reinstalling etc.

### Expected Behavior

spin version should show the spin version

### Steps To Reproduce

Install spin in WSL 2
run spin version

### Environment

```markdown
Linux QUANTUM-DESKTOP 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by quantumwebco** [comment]
Running the following helped
```sudo apt-get install -y dos2unix```
```sudo find ~/.spin -type f -exec dos2unix {} \;```

**Comment by jaydrogers** [comment]
Are you running the command in a DOS prompt? Or are you running `wsl` first, then running the install commands within a bash shell?

**Comment by quantumwebco** [comment]
Running in ```wsl.exe```

**Comment by jaydrogers** [comment]
Can you update to the latest version and try running this again? The Spin 2.0 release is out and it came with a ton of improvements.

A full video is available here: https://x.com/jaydrogers/status/1823751739016913178

I will close this issue for now, but can re-open if the issue persists.

**Comment by quantumwebco** [comment]
I get this when running ```spin init``` now
![image](https://github.com/user-attachments/assets/d66c7a77-5342-439a-b249-9b60058e05b0)
